GET http://127.0.0.1:8080/api/public
content-type: application/json

####
GET http://127.0.0.1:8080/api/secured
content-type: application/json
Authorization: Basic admin:admin

####
GET http://127.0.0.1:8080/api/user
content-type: application/json
Authorization: Basic user:user

####
GET http://127.0.0.1:8080/api/secured
content-type: application/json
Authorization: Basic user:user


